import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
    state: {
        faqList: [
            { id: 1, guid: '1', categoryId: 1, quesion: 'What is The Puf Box?', answer: 'The Puf Box, unlike its name, is for dogs lovers (at heart and loyalty wise) and for dog nation enthusiasts (yes, we are signing the petition soon). It is a monthly subscription box that aims to be a one-stop solution for all your doggo care needs. It has an assortment of food, treats, grooming products, toys, accessories and much more that has been carefully selected to meet the Breed-Age-Preference requirements of your furry friend.' },
            { id: 2, guid: '2', categoryId: 1, quesion: 'What do you get in The Puf Box?', answer: 'Well, everything that can get your dog their first date with that proud Pomeranian who would just not give a damn about them otherwise. The Dog Box hosts pet care products like softening shampoos, fragrant colognes, mlem inducing treats, moisturising paw butters, and tail-chasing toys among a variety of products that are sure to delight your pet.So, go ahead and choose from our range of 3 wonderfully curated boxes of unconditional pet care.P.S First impression is important, guys!' },
            { id: 3, guid: '3', categoryId: 1, quesion: 'What are the types of boxes that you offer?', answer: 'We offer 3 types of boxes; The Shiny Silver Wag-On, The Bold Gold Wag-On, and The Plucky Platinum Wag-On. Thereby, giving you the power to choose how you wish to pamper your furry babies! Each of these boxes has been carefully curated for your furry friends. It can also be customised as per their personas!The Dog Box only gives you what you need for your pup. There is a box catering to every woof under any roof! Did that rhyme scheme land properly? Well, even if that didn’t, we are sure, our boxes will land at your doorsteps properly and on time!' },
            { id: 4, guid: '4', categoryId: 1, quesion: 'How do I claim my referral?', answer: 'Once you have referred someone please get in touch with our team by emailing us at info@thedogbox.in or whatsapp us at +919513918181 with the details of your referee within 5 days of their purchase.' },
            { id: 5, guid: '5', categoryId: 1, quesion: 'How does your referral programme work?', answer: 'What if we told you that you could share your dog box experience with others and get rewarded for it! Currently, if you refer any new customer to us, your friend and you both get a 15% discount on your next billing cycle respectively (Max discount is upto 15% of the bill value of your referral).' },
            { id: 6, guid: '6', categoryId: 1, quesion: 'Is The Dog Box hiring?', answer: 'We are always on the lookout for fresh new talent. If you feel you fit into our culture please email us your resume/cv to info@thedogbox.in along with the position that you feel you are best suited for.' },
            { id: 7, guid: '7', categoryId: 1, quesion: 'Want to partner with us?', answer: 'To partner with us or onboard your brands products onto our platform, please write an email to info@thedogbox.in and attach your brand details, social media handles, product catalogue and any other information that you might seem fit.' }
        ],
        breedList: [{ "breedName": "Affenpinscher", "breedId": 1 },
            { "breedName": "Afghan Hound", "breedId": 2 },
            { "breedName": "Aidi", "breedId": 3 },
            { "breedName": "Airedale Terrier", "breedId": 4 },
            { "breedName": "Akbash Dog", "breedId": 5 },
            { "breedName": "Akita", "breedId": 6 },
            { "breedName": "Alano Español", "breedId": 7 },
            { "breedName": "Alaskan Klee Kai", "breedId": 8 },
            { "breedName": "Alaskan Malamute", "breedId": 9 },
            { "breedName": "Alpine Dachsbracke", "breedId": 10 },
            { "breedName": "Alpine Spaniel", "breedId": 11 },
            { "breedName": "American Bulldog", "breedId": 12 },
            { "breedName": "American Cocker Spaniel", "breedId": 13 },
            { "breedName": "American Eskimo Dog", "breedId": 14 },
            { "breedName": "American Foxhound", "breedId": 15 },
            { "breedName": "American Hairless Terrier", "breedId": 16 },
            { "breedName": "American Pit Bull Terrier", "breedId": 17 },
            { "breedName": "American Staffordshire Terrier", "breedId": 18 },
            { "breedName": "American Water Spaniel", "breedId": 19 },
            { "breedName": "Anglo-Français de Petite Vénerie", "breedId": 20 },
            { "breedName": "Appenzeller Sennenhund", "breedId": 21 },
            { "breedName": "Ariege Pointer", "breedId": 22 },
            { "breedName": "Ariegeois", "breedId": 23 },
            { "breedName": "Armant", "breedId": 24 },
            { "breedName": "Armenian Gampr dog", "breedId": 25 },
            { "breedName": "Artois Hound", "breedId": 26 },
            { "breedName": "Australian Cattle Dog", "breedId": 27 },
            { "breedName": "Australian Kelpie", "breedId": 28 },
            { "breedName": "Australian Shepherd", "breedId": 29 },
            { "breedName": "Australian Silky Terrier", "breedId": 30 },
            { "breedName": "Australian Stumpy Tail Cattle Dog", "breedId": 31 },
            { "breedName": "Australian Terrier", "breedId": 32 },
            { "breedName": "Azawakh", "breedId": 33 },
            { "breedName": "Bakharwal Dog", "breedId": 34 },
            { "breedName": "Barbet", "breedId": 35 },
            { "breedName": "Basenji", "breedId": 36 },
            { "breedName": "Basque Shepherd Dog", "breedId": 37 },
            { "breedName": "Basset Artésien Normand", "breedId": 38 },
            { "breedName": "Basset Bleu de Gascogne", "breedId": 39 },
            { "breedName": "Basset Fauve de Bretagne", "breedId": 40 },
            { "breedName": "Basset Hound", "breedId": 41 },
            { "breedName": "Bavarian Mountain Hound", "breedId": 42 },
            { "breedName": "Beagle", "breedId": 43 },
            { "breedName": "Beagle-Harrier", "breedId": 44 },
            { "breedName": "Bearded Collie", "breedId": 45 },
            { "breedName": "Beauceron", "breedId": 46 },
            { "breedName": "Bedlington Terrier", "breedId": 47 },
            { "breedName": "Belgian Shepherd Dog (Groenendael)", "breedId": 48 },
            { "breedName": "Belgian Shepherd Dog (Laekenois)", "breedId": 49 },
            { "breedName": "Belgian Shepherd Dog (Malinois)", "breedId": 50 },
            { "breedName": "Bergamasco Shepherd", "breedId": 51 },
            { "breedName": "Berger Blanc Suisse", "breedId": 52 },
            { "breedName": "Berger Picard", "breedId": 53 },
            { "breedName": "Berner Laufhund", "breedId": 54 },
            { "breedName": "Bernese Mountain Dog", "breedId": 55 },
            { "breedName": "Billy", "breedId": 56 },
            { "breedName": "Black and Tan Coonhound", "breedId": 57 },
            { "breedName": "Black and Tan Virginia Foxhound", "breedId": 58 },
            { "breedName": "Black Norwegian Elkhound", "breedId": 59 },
            { "breedName": "Black Russian Terrier", "breedId": 60 },
            { "breedName": "Bloodhound", "breedId": 61 },
            { "breedName": "Blue Lacy", "breedId": 62 },
            { "breedName": "Blue Paul Terrier", "breedId": 63 },
            { "breedName": "Boerboel", "breedId": 64 },
            { "breedName": "Bohemian Shepherd", "breedId": 65 },
            { "breedName": "Bolognese", "breedId": 66 },
            { "breedName": "Border Collie", "breedId": 67 },
            { "breedName": "Border Terrier", "breedId": 68 },
            { "breedName": "Borzoi", "breedId": 69 },
            { "breedName": "Boston Terrier", "breedId": 70 },
            { "breedName": "Bouvier des Ardennes", "breedId": 71 },
            { "breedName": "Bouvier des Flandres", "breedId": 72 },
            { "breedName": "Boxer", "breedId": 73 },
            { "breedName": "Boykin Spaniel", "breedId": 74 },
            { "breedName": "Bracco Italiano", "breedId": 75 },
            { "breedName": "Braque d'Auvergne", "breedId": 76 },
            { "breedName": "Braque du Bourbonnais", "breedId": 77 },
            { "breedName": "Braque du Puy", "breedId": 78 },
            { "breedName": "Braque Francais", "breedId": 79 },
            { "breedName": "Braque Saint-Germain", "breedId": 80 },
            { "breedName": "Brazilian Terrier", "breedId": 81 },
            { "breedName": "Briard", "breedId": 82 },
            { "breedName": "Briquet Griffon Vendéen", "breedId": 83 },
            { "breedName": "Brittany", "breedId": 84 },
            { "breedName": "Broholmer", "breedId": 85 },
            { "breedName": "Bruno Jura Hound", "breedId": 86 },
            { "breedName": "Bucovina Shepherd Dog", "breedId": 87 },
            { "breedName": "Bull and Terrier", "breedId": 88 },
            { "breedName": "Bull Terrier (Miniature)", "breedId": 89 },
            { "breedName": "Bull Terrier", "breedId": 90 },
            { "breedName": "Bulldog", "breedId": 91 },
            { "breedName": "Bullenbeisser", "breedId": 92 },
            { "breedName": "Bullmastiff", "breedId": 93 },
            { "breedName": "Bully Kutta", "breedId": 94 },
            { "breedName": "Burgos Pointer", "breedId": 95 },
            { "breedName": "Cairn Terrier", "breedId": 96 },
            { "breedName": "Canaan Dog", "breedId": 97 },
            { "breedName": "Canadian Eskimo Dog", "breedId": 98 },
            { "breedName": "Cane Corso", "breedId": 99 },
            { "breedName": "Cardigan Welsh Corgi", "breedId": 100 },
            { "breedName": "Carolina Dog", "breedId": 101 },
            { "breedName": "Carpathian Shepherd Dog", "breedId": 102 },
            { "breedName": "Catahoula Cur", "breedId": 103 },
            { "breedName": "Catalan Sheepdog", "breedId": 104 },
            { "breedName": "Caucasian Shepherd Dog", "breedId": 105 },
            { "breedName": "Cavalier King Charles Spaniel", "breedId": 106 },
            { "breedName": "Central Asian Shepherd Dog", "breedId": 107 },
            { "breedName": "Cesky Fousek", "breedId": 108 },
            { "breedName": "Cesky Terrier", "breedId": 109 },
            { "breedName": "Chesapeake Bay Retriever", "breedId": 110 },
            { "breedName": "Chien Français Blanc et Noir", "breedId": 111 },
            { "breedName": "Chien Français Blanc et Orange", "breedId": 112 },
            { "breedName": "Chien Français Tricolore", "breedId": 113 },
            { "breedName": "Chien-gris", "breedId": 114 },
            { "breedName": "Chihuahua", "breedId": 115 },
            { "breedName": "Chilean Fox Terrier", "breedId": 116 },
            { "breedName": "Chinese Chongqing Dog", "breedId": 117 },
            { "breedName": "Chinese Crested Dog", "breedId": 118 },
            { "breedName": "Chinese Imperial Dog", "breedId": 119 },
            { "breedName": "Chinook", "breedId": 120 },
            { "breedName": "Chippiparai", "breedId": 121 },
            { "breedName": "Chow Chow", "breedId": 122 },
            { "breedName": "Cierny Sery", "breedId": 123 },
            { "breedName": "Cimarrón Uruguayo", "breedId": 124 },
            { "breedName": "Cirneco dell'Etna", "breedId": 125 },
            { "breedName": "Clumber Spaniel", "breedId": 126 },
            { "breedName": "Combai", "breedId": 127 },
            { "breedName": "Cordoba Fighting Dog", "breedId": 128 },
            { "breedName": "Coton de Tulear", "breedId": 129 },
            { "breedName": "Cretan Hound", "breedId": 130 },
            { "breedName": "Croatian Sheepdog", "breedId": 131 },
            { "breedName": "Cumberland Sheepdog", "breedId": 132 },
            { "breedName": "Curly Coated Retriever", "breedId": 133 },
            { "breedName": "Cursinu", "breedId": 134 },
            { "breedName": "Cão da Serra de Aires", "breedId": 135 },
            { "breedName": "Cão de Castro Laboreiro", "breedId": 136 },
            { "breedName": "Cão Fila de São Miguel", "breedId": 137 },
            { "breedName": "Dachshund", "breedId": 138 },
            { "breedName": "Dalmatian", "breedId": 139 },
            { "breedName": "Dandie Dinmont Terrier", "breedId": 140 },
            { "breedName": "Danish Swedish Farmdog", "breedId": 141 },
            { "breedName": "Deutsche Bracke", "breedId": 142 },
            { "breedName": "Doberman Pinscher", "breedId": 143 },
            { "breedName": "Dogo Argentino", "breedId": 144 },
            { "breedName": "Dogo Cubano", "breedId": 145 },
            { "breedName": "Dogue de Bordeaux", "breedId": 146 },
            { "breedName": "Drentse Patrijshond", "breedId": 147 },
            { "breedName": "Drever", "breedId": 148 },
            { "breedName": "Dunker", "breedId": 149 },
            { "breedName": "Dutch Shepherd Dog", "breedId": 150 },
            { "breedName": "Dutch Smoushond", "breedId": 151 },
            { "breedName": "East Siberian Laika", "breedId": 152 },
            { "breedName": "East-European Shepherd", "breedId": 153 },
            { "breedName": "Elo", "breedId": 154 },
            { "breedName": "English Cocker Spaniel", "breedId": 155 },
            { "breedName": "English Foxhound", "breedId": 156 },
            { "breedName": "English Mastiff", "breedId": 157 },
            { "breedName": "English Setter", "breedId": 158 },
            { "breedName": "English Shepherd", "breedId": 159 },
            { "breedName": "English Springer Spaniel", "breedId": 160 },
            { "breedName": "English Toy Terrier (Black &amp; Tan)", "breedId": 161 },
            { "breedName": "English Water Spaniel", "breedId": 162 },
            { "breedName": "English White Terrier", "breedId": 163 },
            { "breedName": "Entlebucher Mountain Dog", "breedId": 164 },
            { "breedName": "Estonian Hound", "breedId": 165 },
            { "breedName": "Estrela Mountain Dog", "breedId": 166 },
            { "breedName": "Eurasier", "breedId": 167 },
            { "breedName": "Field Spaniel", "breedId": 168 },
            { "breedName": "Fila Brasileiro", "breedId": 169 },
            { "breedName": "Finnish Hound", "breedId": 170 },
            { "breedName": "Finnish Lapphund", "breedId": 171 },
            { "breedName": "Finnish Spitz", "breedId": 172 },
            { "breedName": "Flat-Coated Retriever", "breedId": 173 },
            { "breedName": "Formosan Mountain Dog", "breedId": 174 },
            { "breedName": "Fox Terrier (Smooth)", "breedId": 175 },
            { "breedName": "French Bulldog", "breedId": 176 },
            { "breedName": "French Spaniel", "breedId": 177 },
            { "breedName": "Galgo Español", "breedId": 178 },
            { "breedName": "Gascon Saintongeois", "breedId": 179 },
            { "breedName": "German Longhaired Pointer", "breedId": 180 },
            { "breedName": "German Pinscher", "breedId": 181 },
            { "breedName": "German Shepherd", "breedId": 182 },
            { "breedName": "German Shorthaired Pointer", "breedId": 183 },
            { "breedName": "German Spaniel", "breedId": 184 },
            { "breedName": "German Spitz", "breedId": 185 },
            { "breedName": "German Wirehaired Pointer", "breedId": 186 },
            { "breedName": "Giant Schnauzer", "breedId": 187 },
            { "breedName": "Glen of Imaal Terrier", "breedId": 188 },
            { "breedName": "Golden Retriever", "breedId": 189 },
            { "breedName": "Gordon Setter", "breedId": 190 },
            { "breedName": "Gran Mastín de Borínquen", "breedId": 191 },
            { "breedName": "Grand Anglo-Français Blanc et Noir", "breedId": 192 },
            { "breedName": "Grand Anglo-Français Blanc et Orange", "breedId": 193 },
            { "breedName": "Grand Anglo-Français Tricolore", "breedId": 194 },
            { "breedName": "Grand Basset Griffon Vendéen", "breedId": 195 },
            { "breedName": "Grand Bleu de Gascogne", "breedId": 196 },
            { "breedName": "Grand Griffon Vendéen", "breedId": 197 },
            { "breedName": "Great Dane", "breedId": 198 },
            { "breedName": "Great Pyrenees", "breedId": 199 },
            { "breedName": "Greater Swiss Mountain Dog", "breedId": 200 },
            { "breedName": "Greek Harehound", "breedId": 201 },
            { "breedName": "Greenland Dog", "breedId": 202 },
            { "breedName": "Greyhound", "breedId": 203 },
            { "breedName": "Griffon Bleu de Gascogne", "breedId": 204 },
            { "breedName": "Griffon Bruxellois", "breedId": 205 },
            { "breedName": "Griffon Fauve de Bretagne", "breedId": 206 },
            { "breedName": "Griffon Nivernais", "breedId": 207 },
            { "breedName": "Hamiltonstövare", "breedId": 208 },
            { "breedName": "Hanover Hound", "breedId": 209 },
            { "breedName": "Hare Indian Dog", "breedId": 210 },
            { "breedName": "Harrier", "breedId": 211 },
            { "breedName": "Havanese", "breedId": 212 },
            { "breedName": "Hawaiian Poi Dog", "breedId": 213 },
            { "breedName": "Himalayan Sheepdog", "breedId": 214 },
            { "breedName": "Hokkaido", "breedId": 215 },
            { "breedName": "Hovawart", "breedId": 216 },
            { "breedName": "Huntaway", "breedId": 217 },
            { "breedName": "Hygenhund", "breedId": 218 },
            { "breedName": "Ibizan Hound", "breedId": 219 },
            { "breedName": "Icelandic Sheepdog", "breedId": 220 },
            { "breedName": "Indian pariah dog", "breedId": 221 },
            { "breedName": "Indian Spitz", "breedId": 222 },
            { "breedName": "Irish Red and White Setter", "breedId": 223 },
            { "breedName": "Irish Setter", "breedId": 224 },
            { "breedName": "Irish Terrier", "breedId": 225 },
            { "breedName": "Irish Water Spaniel", "breedId": 226 },
            { "breedName": "Irish Wolfhound", "breedId": 227 },
            { "breedName": "Istrian Coarse-haired Hound", "breedId": 228 },
            { "breedName": "Istrian Shorthaired Hound", "breedId": 229 },
            { "breedName": "Italian Greyhound", "breedId": 230 },
            { "breedName": "Jack Russell Terrier", "breedId": 231 },
            { "breedName": "Jagdterrier", "breedId": 232 },
            { "breedName": "Jämthund", "breedId": 233 },
            { "breedName": "Kai Ken", "breedId": 234 },
            { "breedName": "Kaikadi", "breedId": 235 },
            { "breedName": "Kanni", "breedId": 236 },
            { "breedName": "Karelian Bear Dog", "breedId": 237 },
            { "breedName": "Karst Shepherd", "breedId": 238 },
            { "breedName": "Keeshond", "breedId": 239 },
            { "breedName": "Kerry Beagle", "breedId": 240 },
            { "breedName": "Kerry Blue Terrier", "breedId": 241 },
            { "breedName": "King Charles Spaniel", "breedId": 242 },
            { "breedName": "King Shepherd", "breedId": 243 },
            { "breedName": "Kintamani", "breedId": 244 },
            { "breedName": "Kishu", "breedId": 245 },
            { "breedName": "Komondor", "breedId": 246 },
            { "breedName": "Kooikerhondje", "breedId": 247 },
            { "breedName": "Koolie", "breedId": 248 },
            { "breedName": "Korean Jindo Dog", "breedId": 249 },
            { "breedName": "Kromfohrländer", "breedId": 250 },
            { "breedName": "Kumaon Mastiff", "breedId": 251 },
            { "breedName": "Kurī", "breedId": 252 },
            { "breedName": "Kuvasz", "breedId": 253 },
            { "breedName": "Kyi-Leo", "breedId": 254 },
            { "breedName": "Labrador Husky", "breedId": 255 },
            { "breedName": "Labrador Retriever", "breedId": 256 },
            { "breedName": "Lagotto Romagnolo", "breedId": 257 },
            { "breedName": "Lakeland Terrier", "breedId": 258 },
            { "breedName": "Lancashire Heeler", "breedId": 259 },
            { "breedName": "Landseer", "breedId": 260 },
            { "breedName": "Lapponian Herder", "breedId": 261 },
            { "breedName": "Large Münsterländer", "breedId": 262 },
            { "breedName": "Leonberger", "breedId": 263 },
            { "breedName": "Lhasa Apso", "breedId": 264 },
            { "breedName": "Lithuanian Hound", "breedId": 265 },
            { "breedName": "Longhaired Whippet", "breedId": 266 },
            { "breedName": "Löwchen", "breedId": 267 },
            { "breedName": "Mahratta Greyhound", "breedId": 268 },
            { "breedName": "Maltese", "breedId": 269 },
            { "breedName": "Manchester Terrier", "breedId": 270 },
            { "breedName": "Maremma Sheepdog", "breedId": 271 },
            { "breedName": "McNab", "breedId": 272 },
            { "breedName": "Mexican Hairless Dog", "breedId": 273 },
            { "breedName": "Miniature American Shepherd", "breedId": 274 },
            { "breedName": "Miniature Australian Shepherd", "breedId": 275 },
            { "breedName": "Miniature Fox Terrier", "breedId": 276 },
            { "breedName": "Miniature Pinscher", "breedId": 277 },
            { "breedName": "Miniature Schnauzer", "breedId": 278 },
            { "breedName": "Miniature Shar Pei", "breedId": 279 },
            { "breedName": "Molossus", "breedId": 280 },
            { "breedName": "Montenegrin Mountain Hound", "breedId": 281 },
            { "breedName": "Moscow Watchdog", "breedId": 282 },
            { "breedName": "Moscow Water Dog", "breedId": 283 },
            { "breedName": "Mountain Cur", "breedId": 284 },
            { "breedName": "Mucuchies", "breedId": 285 },
            { "breedName": "Mudhol Hound", "breedId": 286 },
            { "breedName": "Mudi", "breedId": 287 },
            { "breedName": "Neapolitan Mastiff", "breedId": 288 },
            { "breedName": "New Zealand Heading Dog", "breedId": 289 },
            { "breedName": "Newfoundland", "breedId": 290 },
            { "breedName": "Norfolk Spaniel", "breedId": 291 },
            { "breedName": "Norfolk Terrier", "breedId": 292 },
            { "breedName": "Norrbottenspets", "breedId": 293 },
            { "breedName": "North Country Beagle", "breedId": 294 },
            { "breedName": "Northern Inuit Dog", "breedId": 295 },
            { "breedName": "Norwegian Buhund", "breedId": 296 },
            { "breedName": "Norwegian Elkhound", "breedId": 297 },
            { "breedName": "Norwegian Lundehund", "breedId": 298 },
            { "breedName": "Norwich Terrier", "breedId": 299 },
            { "breedName": "Old Croatian Sighthound", "breedId": 300 },
            { "breedName": "Old Danish Pointer", "breedId": 301 },
            { "breedName": "Old English Sheepdog", "breedId": 302 },
            { "breedName": "Old English Terrier", "breedId": 303 },
            { "breedName": "Old German Shepherd Dog", "breedId": 304 },
            { "breedName": "Olde English Bulldogge", "breedId": 305 },
            { "breedName": "Otterhound", "breedId": 306 },
            { "breedName": "Pachon Navarro", "breedId": 307 },
            { "breedName": "Paisley Terrier", "breedId": 308 },
            { "breedName": "Pandikona", "breedId": 309 },
            { "breedName": "Papillon", "breedId": 310 },
            { "breedName": "Parson Russell Terrier", "breedId": 311 },
            { "breedName": "Patterdale Terrier", "breedId": 312 },
            { "breedName": "Pekingese", "breedId": 313 },
            { "breedName": "Pembroke Welsh Corgi", "breedId": 314 },
            { "breedName": "Perro de Presa Canario", "breedId": 315 },
            { "breedName": "Perro de Presa Mallorquin", "breedId": 316 },
            { "breedName": "Peruvian Hairless Dog", "breedId": 317 },
            { "breedName": "Petit Basset Griffon Vendéen", "breedId": 318 },
            { "breedName": "Petit Bleu de Gascogne", "breedId": 319 },
            { "breedName": "Phalène", "breedId": 320 },
            { "breedName": "Pharaoh Hound", "breedId": 321 },
            { "breedName": "Phu Quoc ridgeback dog", "breedId": 322 },
            { "breedName": "Picardy Spaniel", "breedId": 323 },
            { "breedName": "Plott Hound", "breedId": 324 },
            { "breedName": "Podenco Canario", "breedId": 325 },
            { "breedName": "Pointer (dog breed)", "breedId": 326 },
            { "breedName": "Polish Greyhound", "breedId": 327 },
            { "breedName": "Polish Hound", "breedId": 328 },
            { "breedName": "Polish Hunting Dog", "breedId": 329 },
            { "breedName": "Polish Lowland Sheepdog", "breedId": 330 },
            { "breedName": "Polish Tatra Sheepdog", "breedId": 331 },
            { "breedName": "Pomeranian", "breedId": 332 },
            { "breedName": "Pont-Audemer Spaniel", "breedId": 333 },
            { "breedName": "Poodle", "breedId": 334 },
            { "breedName": "Porcelaine", "breedId": 335 },
            { "breedName": "Portuguese Podengo", "breedId": 336 },
            { "breedName": "Portuguese Pointer", "breedId": 337 },
            { "breedName": "Portuguese Water Dog", "breedId": 338 },
            { "breedName": "Posavac Hound", "breedId": 339 },
            { "breedName": "Pražský Krysařík", "breedId": 340 },
            { "breedName": "Pudelpointer", "breedId": 341 },
            { "breedName": "Pug", "breedId": 342 },
            { "breedName": "Puli", "breedId": 343 },
            { "breedName": "Pumi", "breedId": 344 },
            { "breedName": "Pungsan Dog", "breedId": 345 },
            { "breedName": "Pyrenean Mastiff", "breedId": 346 },
            { "breedName": "Pyrenean Shepherd", "breedId": 347 },
            { "breedName": "Rafeiro do Alentejo", "breedId": 348 },
            { "breedName": "Rajapalayam", "breedId": 349 },
            { "breedName": "Rampur Greyhound", "breedId": 350 },
            { "breedName": "Rastreador Brasileiro", "breedId": 351 },
            { "breedName": "Rat Terrier", "breedId": 352 },
            { "breedName": "Ratonero Bodeguero Andaluz", "breedId": 353 },
            { "breedName": "Redbone Coonhound", "breedId": 354 },
            { "breedName": "Rhodesian Ridgeback", "breedId": 355 },
            { "breedName": "Rottweiler", "breedId": 356 },
            { "breedName": "Rough Collie", "breedId": 357 },
            { "breedName": "Russell Terrier", "breedId": 358 },
            { "breedName": "Russian Spaniel", "breedId": 359 },
            { "breedName": "Russian tracker", "breedId": 360 },
            { "breedName": "Russo-European Laika", "breedId": 361 },
            { "breedName": "Sabueso Español", "breedId": 362 },
            { "breedName": "Saint-Usuge Spaniel", "breedId": 363 },
            { "breedName": "Sakhalin Husky", "breedId": 364 },
            { "breedName": "Saluki", "breedId": 365 },
            { "breedName": "Samoyed", "breedId": 366 },
            { "breedName": "Sapsali", "breedId": 367 },
            { "breedName": "Schapendoes", "breedId": 368 },
            { "breedName": "Schillerstövare", "breedId": 369 },
            { "breedName": "Schipperke", "breedId": 370 },
            { "breedName": "Schweizer Laufhund", "breedId": 371 },
            { "breedName": "Schweizerischer Niederlaufhund", "breedId": 372 },
            { "breedName": "Scotch Collie", "breedId": 373 },
            { "breedName": "Scottish Deerhound", "breedId": 374 },
            { "breedName": "Scottish Terrier", "breedId": 375 },
            { "breedName": "Sealyham Terrier", "breedId": 376 },
            { "breedName": "Segugio Italiano", "breedId": 377 },
            { "breedName": "Seppala Siberian Sleddog", "breedId": 378 },
            { "breedName": "Serbian Hound", "breedId": 379 },
            { "breedName": "Serbian Tricolour Hound", "breedId": 380 },
            { "breedName": "Shar Pei", "breedId": 381 },
            { "breedName": "Shetland Sheepdog", "breedId": 382 },
            { "breedName": "Shiba Inu", "breedId": 383 },
            { "breedName": "Shih Tzu", "breedId": 384 },
            { "breedName": "Shikoku", "breedId": 385 },
            { "breedName": "Shiloh Shepherd Dog", "breedId": 386 },
            { "breedName": "Siberian Husky", "breedId": 387 },
            { "breedName": "Silken Windhound", "breedId": 388 },
            { "breedName": "Sinhala Hound", "breedId": 389 },
            { "breedName": "Skye Terrier", "breedId": 390 },
            { "breedName": "Sloughi", "breedId": 391 },
            { "breedName": "Slovak Cuvac", "breedId": 392 },
            { "breedName": "Slovakian Rough-haired Pointer", "breedId": 393 },
            { "breedName": "Small Greek Domestic Dog", "breedId": 394 },
            { "breedName": "Small Münsterländer", "breedId": 395 },
            { "breedName": "Smooth Collie", "breedId": 396 },
            { "breedName": "South Russian Ovcharka", "breedId": 397 },
            { "breedName": "Southern Hound", "breedId": 398 },
            { "breedName": "Spanish Mastiff", "breedId": 399 },
            { "breedName": "Spanish Water Dog", "breedId": 400 },
            { "breedName": "Spinone Italiano", "breedId": 401 },
            { "breedName": "Sporting Lucas Terrier", "breedId": 402 },
            { "breedName": "St. Bernard", "breedId": 403 },
            { "breedName": "St. John's water dog", "breedId": 404 },
            { "breedName": "Stabyhoun", "breedId": 405 },
            { "breedName": "Staffordshire Bull Terrier", "breedId": 406 },
            { "breedName": "Standard Schnauzer", "breedId": 407 },
            { "breedName": "Stephens Cur", "breedId": 408 },
            { "breedName": "Styrian Coarse-haired Hound", "breedId": 409 },
            { "breedName": "Sussex Spaniel", "breedId": 410 },
            { "breedName": "Swedish Lapphund", "breedId": 411 },
            { "breedName": "Swedish Vallhund", "breedId": 412 },
            { "breedName": "Tahltan Bear Dog", "breedId": 413 },
            { "breedName": "Taigan", "breedId": 414 },
            { "breedName": "Talbot", "breedId": 415 },
            { "breedName": "Tamaskan Dog", "breedId": 416 },
            { "breedName": "Teddy Roosevelt Terrier", "breedId": 417 },
            { "breedName": "Telomian", "breedId": 418 },
            { "breedName": "Tenterfield Terrier", "breedId": 419 },
            { "breedName": "Thai Bangkaew Dog", "breedId": 420 },
            { "breedName": "Thai Ridgeback", "breedId": 421 },
            { "breedName": "Tibetan Mastiff", "breedId": 422 },
            { "breedName": "Tibetan Spaniel", "breedId": 423 },
            { "breedName": "Tibetan Terrier", "breedId": 424 },
            { "breedName": "Tornjak", "breedId": 425 },
            { "breedName": "Tosa", "breedId": 426 },
            { "breedName": "Toy Bulldog", "breedId": 427 },
            { "breedName": "Toy Fox Terrier", "breedId": 428 },
            { "breedName": "Toy Manchester Terrier", "breedId": 429 },
            { "breedName": "Toy Trawler Spaniel", "breedId": 430 },
            { "breedName": "Transylvanian Hound", "breedId": 431 },
            { "breedName": "Treeing Cur", "breedId": 432 },
            { "breedName": "Treeing Walker Coonhound", "breedId": 433 },
            { "breedName": "Trigg Hound", "breedId": 434 },
            { "breedName": "Tweed Water Spaniel", "breedId": 435 },
            { "breedName": "Tyrolean Hound", "breedId": 436 },
            { "breedName": "Vizsla", "breedId": 437 },
            { "breedName": "Volpino Italiano", "breedId": 438 },
            { "breedName": "Weimaraner", "breedId": 439 },
            { "breedName": "Welsh Sheepdog", "breedId": 440 },
            { "breedName": "Welsh Springer Spaniel", "breedId": 441 },
            { "breedName": "Welsh Terrier", "breedId": 442 },
            { "breedName": "West Highland White Terrier", "breedId": 443 },
            { "breedName": "West Siberian Laika", "breedId": 444 },
            { "breedName": "Westphalian Dachsbracke", "breedId": 445 },
            { "breedName": "Wetterhoun", "breedId": 446 },
            { "breedName": "Whippet", "breedId": 447 },
            { "breedName": "White Shepherd", "breedId": 448 },
            { "breedName": "Wire Fox Terrier", "breedId": 449 },
            { "breedName": "Wirehaired Pointing Griffon", "breedId": 450 },
            { "breedName": "Wirehaired Vizsla", "breedId": 451 },
            { "breedName": "Yorkshire Terrier", "breedId": 452 },
            { "breedName": "Šarplaninac", "breedId": 453 }
        ]
    },
    getters: {
        allFaqList: (state) => state.faqList,
        allBreedList: (state) => state.breedList
    },
    mutations: {},
    actions: {}

})